#!/usr/bin/env python3

import sys
if sys.version_info[0] < 3:
    sys.stderr.write("ERROR: pyfrc requires python 3!")
    exit(1)

import inspect
from os.path import dirname, exists, join
import subprocess
from setuptools import find_packages, setup
from urllib.request import urlretrieve

setup_dir = dirname(__file__)
git_dir = join(setup_dir, '.git')
base_package = 'pyfrc'
version_file = join(setup_dir, 'lib', base_package, 'version.py')
versions_match = True

netconsole_version = 'jenkins-stable-2015.326'
putty_version = '0.63'


__version__ = "master"
__putty_version__ = None
__netconsole_version__ = None

# Read the version if it exists
if exists(version_file):
    with open(version_file, 'r') as fp:
        exec(fp.read(), globals())

win32_dir = join('robotpy', 'win32')
rio_dir = join('robotpy', 'roborio')

ext_files = {
    'plink': dict(     ver='putty',
                       dir=win32_dir,
                       fname='plink.exe',
                       uri='http://the.earth.li/~sgtatham/putty/%s/x86/%s'),
       
    'psftp': dict(     ver='putty', 
                       dir=win32_dir,
                       fname='psftp.exe',
                       uri='http://the.earth.li/~sgtatham/putty/%s/x86/%s'),
                      
    'netconsole': dict(ver='netconsole', 
                       dir=rio_dir,
                       fname='netconsole-host',
                       uri='https://github.com/robotpy/allwpilib/raw/%s/eclipse-plugins/edu.wpi.first.wpilib.plugins.java/src/main/resources/java-zip/ant/%s')
}

for name, info in ext_files.items():
    
    dst = join(setup_dir, 'lib', base_package, info['dir'], info['fname'])
    cur_ver = globals()['__%s_version__' % info['ver']]
    new_ver = globals()['%s_version' % info['ver']]
    
    if new_ver == cur_ver and exists(dst):
        continue
    
    versions_match = False
    
    print("Downloading %s" % info['fname'])
    def _reporthook(count, blocksize, totalsize):
        percent = int(count*blocksize*100/totalsize)
        sys.stdout.write("\r%02d%%" % percent)
        sys.stdout.flush()

    uri = info['uri'] % (new_ver, info['fname'])
    urlretrieve(uri, dst, _reporthook)
    print()

# Automatically generate a version.py based on the git version
if exists(git_dir):
    p = subprocess.Popen(["git", "describe", "--tags", "--long", "--dirty=-dirty"],
                         stdout=subprocess.PIPE,
                         stderr=subprocess.PIPE)
    out, err = p.communicate()
    # Make sure the git version has at least one tag
    if err:
        print("Error: You need to create a tag for this repo to use the builder")
        sys.exit(1)

    # Convert git version to PEP440 compliant version
    # - Older versions of pip choke on local identifiers, so we can't include the git commit
    version, commits, local = out.decode('utf-8').rstrip().split('-', 2)
    if commits != '0' or '-dirty' in local:
        version = '%s.post0.dev%s' % (version, commits)
else:
    version = __version__

# Generate a new version.py if required
if not exists(version_file) or __version__ != version or not versions_match:
    with open(version_file, 'w') as fp:
        fp.write(inspect.cleandoc("""
            # Autogenerated by setup.py
            __version__ = '{0}'
            __putty_version__ = '{1}'
            __netconsole_version__ = '{2}'
        """).format(version, putty_version, netconsole_version))

with open(join(setup_dir, 'requirements.txt')) as requirements_file:
    install_requires = requirements_file.readlines()

with open(join(dirname(__file__), 'README.md'), 'r') as readme_file:
    long_description = readme_file.read()

setup(name='pyfrc',
      version=version,
      description='Development tools library for python interpreter used for the FIRST Robotics Competition',
      long_description=long_description,
      author='Dustin Spicuzza, Sam Rosenblum',
      author_email='robotpy@googlegroups.com',
      url='https://github.com/robotpy/pyfrc',
      license='BSD',
      packages=find_packages(where='lib'),
      package_dir={'': 'lib'},
      package_data={'pyfrc': ['robotpy/win32/plink.exe',
                              'robotpy/win32/psftp.exe',
                              'robotpy/roborio/netconsole-host']},
      install_requires=install_requires,
      classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: BSD License',
        'Programming Language :: Python :: 3.4',
        'Topic :: Software Development'
        ],
      entry_points={'robotpy': [
        'coverage = pyfrc.mains.cli_coverage:PyFrcCoverage',
        'deploy = pyfrc.mains.cli_deploy:PyFrcDeploy',
        'profiler = pyfrc.mains.cli_profiler:PyFrcProfiler',
        'sim = pyfrc.mains.cli_sim:PyFrcSim',
        'test = pyfrc.mains.cli_test:PyFrcTest'
      ]}
)



